### ISSUE TITLE
[2-1] - As a customer, I want to have a feature which would allow me to filter out recipes that use a particular ingredient, so I can avoid ingredients that would cause an allergic reaction.

### ISSUE THREAD

**Issue by veraborvinski** [KamilKrauze/agile_project#10]
Filtering system

## Definition of Done
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company colour theme
- Offers alt-text and is user-friendly

## Acceptance Criteria
- [x] Include items
- [x] Exclude items
- [x] Hardcoded ingredients
- [x] Integration with the database - queries for ingredients and recipes
- [x] #11 
- [ ] #14 
- [x] #20

**Comment by last-genius** [comment]
Checkboxes work finally! They modify the parameters in the URL (see screenshot), keep checked status between reloads, and I've even figured out styling...

Next - to connect this up to the database and fill recipes dynamically.

![image](https://user-images.githubusercontent.com/53952748/214377595-dc71da5b-c3da-4978-899c-7fcc9d56e8d5.png)

**Comment by last-genius** [comment]
Implemented the suggestion of (hardcoded) additional ingredients clicking which changes the URL and modifies the list in the original form too. Spent way too much time trying to fix styling in Firefox, in the end had to resort to some JS workarounds.

![image](https://user-images.githubusercontent.com/53952748/214558249-c59ff7a5-cd9b-44e2-ad8d-88c131f83d46.png)

**Comment by last-genius** [comment]
Fixed the ingredients selection (at least I think so) by moving from the `<form>` with `<input>` to little smart links with `<a>`, optimized it for mobile devices, improved the SQL queries we use to get the list of recipes.

Up next: 
* merging this and seeing how it works on Azure
* working on ingredient search and allergens
* seasonal recipes

![image](https://user-images.githubusercontent.com/53952748/216102567-c7396c4d-0b8a-432f-8f4c-6367d1a2689d.png)

**Comment by last-genius** [comment]
Seasonal recipes done :sparkles: 

![image](https://user-images.githubusercontent.com/53952748/216178213-fa35acdb-c4de-4fbf-9b9b-c726cdd858a8.png)
