### ISSUE TITLE
[2-2] - As a member of LGL we want to have a tag about allergies for each ingredient, so our customers are aware of the risks that come with buying our products.

### ISSUE THREAD

**Issue by veraborvinski** [KamilKrauze/agile_project#11]
Allergy label

## Acceptance Criteria
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company colour theme
- Offers alt-text and is user-friendly

## Progress Tracker

**Comment by last-genius** [comment]
We have allergen labels inside recipe pages already, and I also implemented them with the filtering system, allowing users to exclude recipes by selecting allergies:

![image](https://user-images.githubusercontent.com/53952748/216130267-4aa5bc03-1fa3-435e-bff3-41a124120656.png)
