### ISSUE TITLE
[8-1] Featured Social Media Links

### ISSUE THREAD

**Issue by last-genius** [KamilKrauze/agile_project#15]
# Featured Social Media Links

As LGL we would like users to view our social media to create user retention.

## Acceptance Criteria
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company color theme
- Offers alt-text and is user-friendly

## Progress Tracker
- [x]  Footer features stylized links to the social media accounts

**Comment by KamilKrauze** [comment]
Social media links are now in the navbar as styling and consistency was breaking in the footer

**Comment by last-genius** [comment]
I think we should wait until an assigned reviewer looks at an issue before moving it to "Done" (ideally, even until tomorrow's Scrum). This is a simple one so doesn't matter much, but in the future it's better to do it the safe way. Since you didn't create a separate branch for this issue, you should probably link to a commit on `main` where you implemented this.

**Comment by KamilKrauze** [comment]
Yeah the commit that is mostly responsible for this is
[https://github.com/KamilKrauze/agile_project/commit/4ef7d709cbe56c6b0887f5b89feb8c2aa5c3feea](https://github.com/KamilKrauze/agile_project/commit/4ef7d709cbe56c6b0887f5b89feb8c2aa5c3feea)
