### ISSUE TITLE
[6-1] - As a user I would like to have a shopping list based on a number of recipes that I have chosen to make shopping easier.

### ISSUE THREAD

**Issue by DimitarValkov2113** [KamilKrauze/agile_project#17]
Shopping list depending on recipes chosen

## Definition of Done
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company colour theme
- Offers alt-text and is user-friendly
- Being able to choose multiple recipes to make a shopping list

## Acceptance Critieria
- [x] Make recipes being able to be chosen 
- [x] Have a list of all of the ingredients in order to display it to the user

**Comment by last-genius** [comment]
Implemented the shopping list functionality.

You can add recipes to the shopping list from their pages:

![image](https://user-images.githubusercontent.com/53952748/216609938-a8437627-da39-4dfd-bb3d-06c5a5ffc298.png)
![image](https://user-images.githubusercontent.com/53952748/216610080-f1801fe0-b752-4037-a24d-8e68ca58f0d3.png)

- - - 
And view the combined ingredients on the shopping list page: 
![image](https://user-images.githubusercontent.com/53952748/216610178-a91e53a1-a942-4496-8884-a76d93a62f9c.png)

Everything is dynamic and updates when changes are made on the other page, everything is done on the user-side.
