### ISSUE TITLE
[2-4] - As a customer I want to be shown seasonal recipes as I want to use fresh fruit and vegetables in my cooking.

### ISSUE THREAD

**Issue by veraborvinski** [KamilKrauze/agile_project#20]
Featuring Seasonal recipes

## Acceptance Criteria
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company colour theme
- Offers alt-text and is user-friendly

## Progress Tracker
- [x] Categorising recipes into seasons
- [x] Filtering functionality for seasons

**Comment by monberin** [comment]
New tables added to accommodate the seasonal recipes functionality (updated file on eba9eb358d9c627ddbfa468cea73e6f96734cb8a), season filtering functionality implemented on 02b5d5eb80fd904f87c0def36b3bfd652519af72
