### ISSUE TITLE
[1-3] - As a customer I would like to scale ingredients in a recipe so that I only buy the ingredients that I need.

### ISSUE THREAD

**Issue by gatillom** [KamilKrauze/agile_project#26]
Recipe - scaling method for the recipes.

## Definition of Done
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company colour theme
- Offers alt-text and is user-friendly

## Acceptance Criteria
- [x] Fetches the ingredient amount from the recipe table from the database.
- [x] Displays the correct portion amount.
- [x] Ingredients are scaled correctly in relation to the portion quantity.

**Comment by last-genius** [comment]
Implemented now!

![image](https://user-images.githubusercontent.com/53952748/216341992-b1bad642-ae8b-4537-a391-5fe841ca8136.png)
