### ISSUE TITLE
[1-5] AC: Recipe features picture from LDL

### ISSUE THREAD

**Issue by gatillom** [KamilKrauze/agile_project#27]
Recipes should feature a picture from LGL of the main product when the recipe picture in unavailable

## Acceptance Criteria
- [ ] Functions well on mobile and desktop
- [ ] Bootstrap-based styling
- [ ] Follows the company colour theme
- [ ] Offers alt-text and is user-friendly

**Comment by monberin** [comment]
closed by pull request #44: b3f74a01c9fa6321e5a4d90bd819c71ff2b0a686
