### ISSUE TITLE
[1-1] Featured Recipes List

### ISSUE THREAD

**Issue by last-genius** [KamilKrauze/agile_project#3]
# Featured Recipes List

As a user, I want to see a list of most popular recipes to make it easier for me to choose something to cook

## Definition of Done
- [x] Functions well on mobile and desktop
- [x] Bootstrap-based styling
- [x] Follows the company color theme
- [x] Offers alt-text and is user-friendly

## Progress Tracker
- [x] The general look works, but the content is hardcoded
- [x] sample pictures are visible on the recipe cards
- [x] #40
- [x] #4 
- [x] #56

**Comment by last-genius** [comment]
@KamilKrauze could you review [6e8d085](https://github.com/KamilKrauze/agile_project/commit/6e8d085150993b30aba38d17670b3294a00ad95b) please? I've split up the header and the footer into separate files, which simplified the basic template so you might want to consider pulling from this branch into main as well. 

Couldn't figure out the styling completely, but it should work more or less:
![image](https://user-images.githubusercontent.com/53952748/214083191-3834c219-c492-40a9-9735-92a795fe48a4.png)

**Comment by KamilKrauze** [comment]
All good here

**Comment by last-genius** [comment]
Played around with carousels in [c1f6e56](https://github.com/KamilKrauze/agile_project/commit/c1f6e5691ac18ce69e77574d21fd9917e8e8c273) but I don't think it's the right solution for us, so just implemented a nice fade out and kept it as a horizontal scroll block. LMK if it's alright and I can open a pull request later and mark the task in the progress tracker as completed.

![image](https://user-images.githubusercontent.com/53952748/214261554-f72e8782-48ab-4abd-94f1-0cf7bf66bf80.png)
