### ISSUE TITLE
[1-1-2] AC: Optimize for mobile

### ISSUE THREAD

**Issue by DimitarValkov2113** [KamilKrauze/agile_project#56]
### Definition of Done
- [x] Functions well on mobile and desktop
- [x] Bootstrap-based styling
- [x] Follows the company color theme
- [x] Offers alt-text and is user-friendly

**Comment by last-genius** [comment]
Improved the mobile experience substantially, made it more responsive.

![image](https://user-images.githubusercontent.com/53952748/216103421-c3c0a20b-1938-485a-9e66-1b09b664e48b.png)

![image](https://user-images.githubusercontent.com/53952748/216104030-c9fe6605-86c4-484e-acd4-bfd1a09b6c42.png)

Going to close this issue once #59 is merged.
