### ISSUE TITLE
[5-4] - As an admin I want to be able to modify recipes and ingredients to control for misleading or inaccurate information.

### ISSUE THREAD

**Issue by last-genius** [KamilKrauze/agile_project#8]
Admin Panel - Edit Recipes

## Definition of Done
- Functions well on mobile and desktop
- Bootstrap-based styling
- Follows the company colour theme
- Offers alt-text and is user-friendly

**Comment by DimitarValkov2113** [comment]
this is pretty much done. I cannot show anything since it works with the database.
